### ISSUE TITLE
py27 builds are failing

### ISSUE THREAD

**Issue by ceball** [pyviz/nbsmoke#15]
Seems to have started some time ago, from a change in the outside world:

![nbsmokebuilds](https://user-images.githubusercontent.com/1929/54078037-3362b280-42b9-11e9-8e4e-798f4e167933.png)

**Comment by jsignell** [comment]
Do we still need to support python 2.7? @jbednar

**Comment by jbednar** [comment]
I assume so by default.  I guess if you know that when we actually use it we are always on py3 (if our tests only run nbsmoke on one platform variant), then it would be ok to turn off py27 support, but otherwise...

**Comment by ceball** [comment]
Was fixed by #18
